### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by schulze1963** [flathub/com.quixel.Bridge#43]
flatpak install flathub com.quixel.Bridge
Looking for matches…

com.quixel.Bridge permissions:
    ipc      network              pulseaudio      x11
    dri      file access [1]      tags [2]

    [1] xdg-documents
    [2] proprietary

        KENNUNG                    Zweig    Op   Remote   Download
 1. [✓] com.quixel.Bridge.Locale   stable   i    flathub    6,4 kB / 59,9 kB
 2. [✗] com.quixel.Bridge          stable   i    flathub  397,2 MB / 397,0 MB

Error: Falsche Größe für Extradaten https://d2shgxa8i058x8.cloudfront.net/bridge/linux/Bridge.AppImage
Fehler: Failed to installieren com.quixel.Bridge: Falsche Größe für Extradaten https://d2shgxa8i058x8.cloudfront.net/bridge/linux/Bridge.AppImage

**Comment by FakeShemp** [comment]
Solved with #42
